### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset_dir: \\ad.uillinois.edu\engr-ews\haoran27\微调\SFT-DataJudge\data\labeled\scorer_binary_sft_v2
dataset: scorer_binary_v2_conservative_train
eval_dataset: scorer_binary_v2_conservative_valid
template: qwen3_nothink
cutoff_len: 4096
preprocessing_num_workers: 16
dataloader_num_workers: 0

### output
output_dir: C:\Users\haoran27\llamafactory_outputs\scorer_binary_v2_conservative_qwen3_8b_lora_e3
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
gradient_checkpointing: true
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 20
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
do_eval: true
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
